services:

  db:
    image: postgres:18
    container_name: aiopshub-db
    environment:
      POSTGRES_DB: aiopshub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: REMOVED_SECRET
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: ./backend
    container_name: aiopshub-backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:REMOVED_SECRET@db:5432/aiopshub

  prometheus:
    image: prom/prometheus:latest
    container_name: aiopshub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: aiopshub-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
  loki:
    image: grafana/loki:latest
    container_name: aiopshub-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki_data:/loki
  alloy:
    image: grafana/alloy:latest
    container_name: aiopshub-alloy
    depends_on:
      - loki
    ports:
      - "12345:12345"
    volumes:
      - ./monitoring/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - alloy_data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
volumes:
  postgres_data:
  grafana_data:
  loki_data:
  alloy_data: